function [slp] = get_slopes(clks,tr1,tr2,aref)
%get the clock slope ratios between each anchor
%   This function calculates the ratios of the clock slopes between each
%   anchor in the Decawave UWB localisation application
% inputs:
%   clks - the clock array, generated by get_clocks.m
%   tr1 - previous transaction id
%   tr2 - current transaction id
%   aref - id of reference anchor used for calculation

idxcnt=size(clks,2)-1;
slp=ones(idxcnt);
for a1=1:idxcnt
    for a2=1:a1
      cla1=clks(tr1,aref,a1,2);
      cla2=clks(tr2,aref,a1,2);
      if cla1>cla2
          cla2=cla2+2^40;
      end
      
      clb1=clks(tr1,aref,a2,2);
      clb2=clks(tr2,aref,a2,2);
      if clb1>clb2
          clb2=clb2+2^40;
      end
       slp(a1,a2)= (cla2-cla1)/(clb2-clb1);
       slp(a2,a1)=1/slp(a1,a2);
    end
end
end

